title: dajinxiaobei
description: A simple website built with Jekyll and GitHub Pages
baseurl: "" # 项目根路径，通常保持为空
url: "https://upswine.github.io" # 改为你的 GitHub Pages 地址

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap

# 可选项：启用 GitHub Pages 自动构建支持
github:
  is_project_page: true
